"""Configuration constants for dm_api."""

ENV_DM_API_PATH = "DM_API_PATH"
ENV_DM_APP_ID = "DM_APP_ID"
ENV_DM_PUBLIC_KEY = "DM_PUBLIC_KEY"
ENV_DM_LAUNCHER_ENDPOINT = "DM_LAUNCHER_ENDPOINT"
ENV_DM_LAUNCHER_TOKEN = "DM_LAUNCHER_TOKEN"

DEFAULT_DLL_NAME = "dm_api.dll"

DM_ERR_OK = 0
DM_ERR_FAIL = 1
DM_ERR_INVALID_PARAMETER = 2
DM_ERR_APPID_NOT_SET = 3
DM_ERR_LICENSE_KEY_NOT_SET = 4
DM_ERR_NOT_ACTIVATED = 5
DM_ERR_LICENSE_EXPIRED = 6
DM_ERR_NETWORK = 7
DM_ERR_FILE_IO = 8
DM_ERR_SIGNATURE = 9
DM_ERR_BUFFER_TOO_SMALL = 10

ACTIVATION_ERROR_NAMES = {
    DM_ERR_OK: "DM_ERR_OK",
    DM_ERR_FAIL: "DM_ERR_FAIL",
    DM_ERR_INVALID_PARAMETER: "DM_ERR_INVALID_PARAMETER",
    DM_ERR_APPID_NOT_SET: "DM_ERR_APPID_NOT_SET",
    DM_ERR_LICENSE_KEY_NOT_SET: "DM_ERR_LICENSE_KEY_NOT_SET",
    DM_ERR_NOT_ACTIVATED: "DM_ERR_NOT_ACTIVATED",
    DM_ERR_LICENSE_EXPIRED: "DM_ERR_LICENSE_EXPIRED",
    DM_ERR_NETWORK: "DM_ERR_NETWORK",
    DM_ERR_FILE_IO: "DM_ERR_FILE_IO",
    DM_ERR_SIGNATURE: "DM_ERR_SIGNATURE",
    DM_ERR_BUFFER_TOO_SMALL: "DM_ERR_BUFFER_TOO_SMALL",
}

DEV_LICENSE_ERROR = (
    "Development license is missing or corrupted. "
    "Run `distromate sdk renew` to regenerate the dev certificate."
)
